In [8]:
%load_ext autoreload
%autoreload 2
from get_data import *
import pandas as pd
from torch.utils.data import Dataset
import torch
from sklearn.preprocessing import MinMaxScaler
from pickle import load, dump

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
# FOR SCALER

download_data(
    start_date="2020-01-01",
    end_date="2022-02-28",
    currency_symbol="BTCUSDT",
    path="data/scaler_data_15_2020-01-01_2022-02-28",
    ohlcv_size='15m'
)

75598it [01:50, 687.05it/s]


75598


In [11]:
PATH_SCALER_DATA = "data/scaler_data_15_2020-01-01_2022-02-28"

scaler = MinMaxScaler()
scaler_fit_data = get_high_from_data(PATH_SCALER_DATA).reshape(-1, 1)
print(scaler_fit_data)
scaler.fit(scaler_fit_data)
print(scaler.transform(scaler_fit_data))

[[ 7184.57]
 [ 7186.7 ]
 [ 7187.62]
 ...
 [37784.99]
 [38299.39]
 [38040.27]]
[[0.04545791]
 [0.0454908 ]
 [0.04550501]
 ...
 [0.51798376]
 [0.52592703]
 [0.52192575]]


In [12]:
dump(scaler, open('scalers/scaler_15m.pkl', 'wb'))

In [14]:
scaler = load(open('scalers/scaler_15m.pkl', 'rb'))
print(scaler.transform(scaler_fit_data))

[[0.04545791]
 [0.0454908 ]
 [0.04550501]
 ...
 [0.51798376]
 [0.52592703]
 [0.52192575]]
